Proceso sin_titulo
	Escribir "DIGITE EL PRESUPUESTO ANUAL DEL HOSPITAL: " ;
	Leer PRE;
	G<-(PRE*0.40)
	T<-(PRE*0.30)
	P<-(PRE*0.30)
	Mostrar "EL RESULTADO DEL PRESUPUESTO DE LA GINECOLOGIA ES: ",G; 
	Mostrar "EL RESULTADO DEL PRESUPUESTO DE TRAUMATOLOGIA ES: ",T;
	Mostrar "EL RESULTADO DEL PRESUPUESTO DE LA PEDIATRIA ES: ",P;
FinProceso
