Proceso IDENTIFICAR_UN_NUMERO_POSITIVO_O_NEGATIVO
	//ESTE ALGORITMO PERMITE DETERMINAR 
	//SI UN NUMERO ES POSITIVO O NEGATIVO
	Escribir "DIGITE UN NUMERO: " ;
	Leer NUM;
	Si NUM>=0 Entonces
		R="POSITIVO"
	Sino
		R="NEGATIVO"
	FinSi
	Mostrar "EL NUMERO ES: " ,R;
FinProceso
