Proceso sin_titulo
	Escribir "DIGITE EL NUMERO DE HOMBRES: " ;
	Leer NH;
	Escribir "DIOGITE EL NUMERO DE MUJERES: " ;
	Leer NM;
	TA<-NH+NM
	PH<-NH*100/TA
	PM<-NM*100/TA
	Mostrar "EL RESULTADO DEL PORCENTAJE DE MUJERES ES: ",PM;
	Mostrar "EL RESULTADO DEL PORCENTAJE DE HOMBRES ES: ",PH;
	
FinProceso
