Proceso sin_titulo
	//HALLAR EL AREA Y EL PERIMETRO DE UN TRIANGULO
	Escribir "ESCRIBIR UN NUMERO PARA LA BASE DE UN TRIANGULO: " ;
	Leer NB;
	Escribir "ESCRIBIR UN NUMERO PARA LA ALTURA DE UN TRIANGULO: " ;
	Leer NA;
	AREA<-(NB*NA)
	PER<-(2)*(NB+NA)
	Mostrar "EL AREA DE UN TRIANGULO ES: ",AREA; 
	Mostrar "EL PERIMETRO DE UN TRIANGULO ES: ",PER;
FinProceso
