Proceso sin_titulo
	//HALLAR EL RESULTADO CUBICO Y CUADRADO DE CUALQUIER NUMERO
	Escribir "ESCRIBA CUALQUIER NUMERO: " ;
	Leer NUM;
	CUA<-(NUM*NUM)
	CUB<-(NUM^3)
	Mostrar "EL RESULTADO CUADRADO ES: ",CUA;
	Mostrar "EL RESULTADO CUBICO ES: " ,CUB;
FinProceso
	