Proceso sin_titulo
	Escribir "DIGITE EL TIEMPO OBTENIDO DEL LUNES: " ;
	Leer LU;
	Escribir "DIGITE EL TIEMPO OBTENIDO DEL MIERCOLES: " ;
	Leer MI;
	Escribir "DIGITE EL TIEMPO OBTENIDO DEL VIERNES: " ;
	Leer VI;
	SEM<-((LU+MI+VI)/5)
	Mostrar "EL RESULTADO DEL TIEMPO RECORRIDO EN UNA SEMANA CUALQUIRA ES: ",SEM;
FinProceso
